In [ ]:
import numpy as np #import Numpy

In [ ]:
project_data = ("/content/drive/MyDrive/Colab Notebooks/Data processing /KAG_Conversion_Data.csv") #identifiable variable/name to set equal to document

data = np.genfromtxt(project_data,delimiter=",",skip_header=1) # command to genfromtxt the table and show all data relevant minus the header row

In [ ]:
data_str = np.genfromtxt(project_data,delimiter=',',skip_header=1,dtype=str) #turns numpy int/float into str
data_str

array([['708746', '916', '103916', ..., '1.429999948', '2', '1'],
       ['708749', '916', '103917', ..., '1.820000023', '2', '0'],
       ['708771', '916', '103920', ..., '0', '1', '0'],
       ...,
       ['1314412', '1178', '179979', ..., '40.28999949', '2', '0'],
       ['1314414', '1178', '179981', ..., '198.7100005', '8', '2'],
       ['1314415', '1178', '179982', ..., '165.6099987', '5', '2']],
      dtype='<U11')

In [ ]:
print(data) #print array

[[7.08746000e+05 9.16000000e+02 1.03916000e+05 ... 1.42999995e+00
  2.00000000e+00 1.00000000e+00]
 [7.08749000e+05 9.16000000e+02 1.03917000e+05 ... 1.82000002e+00
  2.00000000e+00 0.00000000e+00]
 [7.08771000e+05 9.16000000e+02 1.03920000e+05 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 ...
 [1.31441200e+06 1.17800000e+03 1.79979000e+05 ... 4.02899995e+01
  2.00000000e+00 0.00000000e+00]
 [1.31441400e+06 1.17800000e+03 1.79981000e+05 ... 1.98710001e+02
  8.00000000e+00 2.00000000e+00]
 [1.31441500e+06 1.17800000e+03 1.79982000e+05 ... 1.65609999e+02
  5.00000000e+00 2.00000000e+00]]


In [ ]:
ad_id = data[:,0]               ''' These assign variable/names to colums of information in the table to help Numpy locate the needed features '''
xyzcampaignid = data[:,1]
fbcampaignid = data[:,2]
age = data[:,3]
gender = data[:,4]
interest = data[:,5]
impressions = data[:,6]
clicks = data[:,7]
spent = data[:,8]
total_conversion = data[:,9]
approved_conversion = data[:,10]

In [ ]:
unique_ad = np.unique(xyzcampaignid) #.unique helps factors not repeat in search results
unique_ad

array([ 916.,  936., 1178.])

In [ ]:
unique_ad, count = np.unique(xyzcampaignid,return_counts=True) #COUNT to get number of ...; Boolean type to return unique results requested
print(unique_ad)
print(count)

[ 916.  936. 1178.]
[ 54 464 625]


In [ ]:
for i in range(len(unique_ad)): # For i will go through each individual record related to the request
  print('{} ran {} times'.format(unique_ad[i]) # Ask for output in readable form instead of as an array


916.0 ran 54 times
936.0 ran 464 times
1178.0 ran 625 times


In [ ]:
age = data_str[:,3]
age

array(['30-34', '30-34', '30-34', ..., '45-49', '45-49', '45-49'],
      dtype='<U11')

In [ ]:
age_group = np.unique(age) # notice the change with np.unique to give one specific result if they're repeats
age_group

array(['30-34', '35-39', '40-44', '45-49'], dtype='<U11')

In [ ]:
average_spent = spent.mean() #Average
average_spent

51.36065613141295

In [ ]:
max_spent = spent.max() #Maximum
max_spent

639.9499981

In [ ]:
min_spent = spent.min() #Minimum
min_spent

0.0

In [ ]:
max_clicks = clicks.max() #Clicks
max_clicks

421.0

In [ ]:
ad_id[clicks == max_clicks] #Particular ID with requested info(maximum clicks);Notice use of square brackets and no space

array([1121814.])

In [ ]:
approved_conversion[clicks == max_clicks] #uses the clicks and approved conversion columns to determine how many people purchased after viewing


array([13.])

In [ ]:
max_purchase = approved_conversion.max() #Maximum number of purchases in the database
print(max_purchase)

21.0


In [ ]:
data_str[approved_conversion == max_purchase] #Array represents one complete row of information for one product with the most purchases

array([['1121104', '1178', '144533', '30-34', 'M', '16', '2080666',
        '202', '360.1500015', '40', '21']], dtype='<U11')